//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controles.Serv_CadPessoa {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AtualizarCadastroSoap", Namespace="http://tempuri.org/")]
    public partial class AtualizarCadastro : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AtualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarFilialOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AtualizarCadastro() {
            this.Url = global::Controles.Properties.Settings.Default.Controles_Serv_CadPessoa_AtualizarCadastro;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AtualizarCompletedEventHandler AtualizarCompleted;
        
        /// <remarks/>
        public event AtualizarFilialCompletedEventHandler AtualizarFilialCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Atualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Atualizar(System.Xml.XmlNode XMLCad, int IdUsuario, int IdFilial) {
            object[] results = this.Invoke("Atualizar", new object[] {
                        XMLCad,
                        IdUsuario,
                        IdFilial});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarAsync(System.Xml.XmlNode XMLCad, int IdUsuario, int IdFilial) {
            this.AtualizarAsync(XMLCad, IdUsuario, IdFilial, null);
        }
        
        /// <remarks/>
        public void AtualizarAsync(System.Xml.XmlNode XMLCad, int IdUsuario, int IdFilial, object userState) {
            if ((this.AtualizarOperationCompleted == null)) {
                this.AtualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarOperationCompleted);
            }
            this.InvokeAsync("Atualizar", new object[] {
                        XMLCad,
                        IdUsuario,
                        IdFilial}, this.AtualizarOperationCompleted, userState);
        }
        
        private void OnAtualizarOperationCompleted(object arg) {
            if ((this.AtualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarCompleted(this, new AtualizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtualizarFilial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AtualizarFilial(System.Xml.XmlNode XMLCad, int IdUsuario, int IdFilial) {
            object[] results = this.Invoke("AtualizarFilial", new object[] {
                        XMLCad,
                        IdUsuario,
                        IdFilial});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarFilialAsync(System.Xml.XmlNode XMLCad, int IdUsuario, int IdFilial) {
            this.AtualizarFilialAsync(XMLCad, IdUsuario, IdFilial, null);
        }
        
        /// <remarks/>
        public void AtualizarFilialAsync(System.Xml.XmlNode XMLCad, int IdUsuario, int IdFilial, object userState) {
            if ((this.AtualizarFilialOperationCompleted == null)) {
                this.AtualizarFilialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarFilialOperationCompleted);
            }
            this.InvokeAsync("AtualizarFilial", new object[] {
                        XMLCad,
                        IdUsuario,
                        IdFilial}, this.AtualizarFilialOperationCompleted, userState);
        }
        
        private void OnAtualizarFilialOperationCompleted(object arg) {
            if ((this.AtualizarFilialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarFilialCompleted(this, new AtualizarFilialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AtualizarCompletedEventHandler(object sender, AtualizarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AtualizarFilialCompletedEventHandler(object sender, AtualizarFilialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarFilialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarFilialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591