//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe/services/NfeStatusServico")]
        public string Controles_HNfe_StatusServico_NfeStatusServico {
            get {
                return ((string)(this["Controles_HNfe_StatusServico_NfeStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe/services/NfeRecepcao")]
        public string Controles_HNfe_RecepcaoNfe_NfeRecepcao {
            get {
                return ((string)(this["Controles_HNfe_RecepcaoNfe_NfeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe/services/NfeRetRecepcao")]
        public string Controles_HNfe_RetRecepcaoNfe_NfeRetRecepcao {
            get {
                return ((string)(this["Controles_HNfe_RetRecepcaoNfe_NfeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe/services/NfeCancelamento")]
        public string Controles_HNfe_CancelaNfe_NfeCancelamento {
            get {
                return ((string)(this["Controles_HNfe_CancelaNfe_NfeCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe/services/NfeInutilizacao")]
        public string Controles_HNfe_InutilizacaoNfe_NfeInutilizacao {
            get {
                return ((string)(this["Controles_HNfe_InutilizacaoNfe_NfeInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe/services/NfeConsulta")]
        public string Controles_HNfe_ConsultaNfe_NfeConsulta {
            get {
                return ((string)(this["Controles_HNfe_ConsultaNfe_NfeConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe/services/NfeRecepcao")]
        public string Controles_Nfe_RecepcaoNfe_NfeRecepcao {
            get {
                return ((string)(this["Controles_Nfe_RecepcaoNfe_NfeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe/services/NfeRetRecepcao")]
        public string Controles_Nfe_RetRecepcaoNfe_NfeRetRecepcao {
            get {
                return ((string)(this["Controles_Nfe_RetRecepcaoNfe_NfeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe/services/NfeCancelamento")]
        public string Controles_Nfe_CancelaNfe_NfeCancelamento {
            get {
                return ((string)(this["Controles_Nfe_CancelaNfe_NfeCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe/services/NfeInutilizacao")]
        public string Controles_Nfe_InutilizacaoNfe_NfeInutilizacao {
            get {
                return ((string)(this["Controles_Nfe_InutilizacaoNfe_NfeInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe/services/NfeConsulta")]
        public string Controles_Nfe_ConsultaNfe_NfeConsulta {
            get {
                return ((string)(this["Controles_Nfe_ConsultaNfe_NfeConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe/services/NfeStatusServico")]
        public string Controles_Nfe_StatusServico_NfeStatusServico {
            get {
                return ((string)(this["Controles_Nfe_StatusServico_NfeStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.19.133.130/WSSaldoEstoque/BuscaSaldoEstoque.asmx")]
        public string Controles_Serv_SaldoEstoque_ConsultaSaldo {
            get {
                return ((string)(this["Controles_Serv_SaldoEstoque_ConsultaSaldo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.19.133.130/WSDebitoCliente/DebitoCliente.asmx")]
        public string Controles_Serv_DebitoCliente_DebitoCliente {
            get {
                return ((string)(this["Controles_Serv_DebitoCliente_DebitoCliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.19.133.130/WSCadPessoa/AtualizarCadastro.asmx")]
        public string Controles_Serv_CadPessoa_AtualizarCadastro {
            get {
                return ((string)(this["Controles_Serv_CadPessoa_AtualizarCadastro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.19.133.130/ERP-SGE_WebService/RegFaturamento.asmx")]
        public string Controles_EnviarFinanceiro_RegFaturamento {
            get {
                return ((string)(this["Controles_EnviarFinanceiro_RegFaturamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe2/services/NfeCancelamento2")]
        public string Controles_HNFE_Cancelar2_NfeCancelamento2 {
            get {
                return ((string)(this["Controles_HNFE_Cancelar2_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe2/services/NfeConsulta2")]
        public string Controles_HNFE_Consulta2_NfeConsulta2 {
            get {
                return ((string)(this["Controles_HNFE_Consulta2_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe2/services/NfeInutilizacao2")]
        public string Controles_HNFE_Inutilizacao2_NfeInutilizacao2 {
            get {
                return ((string)(this["Controles_HNFE_Inutilizacao2_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe2/services/NfeRecepcao2")]
        public string Controles_HNFE_Recepcao2_NfeRecepcao2 {
            get {
                return ((string)(this["Controles_HNFE_Recepcao2_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe2/services/NfeRetRecepcao2")]
        public string Controles_HNFE_RetRecepcao2_NfeRetRecepcao2 {
            get {
                return ((string)(this["Controles_HNFE_RetRecepcao2_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br:443/nfe2/services/NfeStatusServico2")]
        public string Controles_HNFE_StatusServico2_NfeStatusServico2 {
            get {
                return ((string)(this["Controles_HNFE_StatusServico2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe2/services/NfeCancelamento2")]
        public string Controles_NFE_Cancelar2_NfeCancelamento2 {
            get {
                return ((string)(this["Controles_NFE_Cancelar2_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe2/services/NfeConsulta2")]
        public string Controles_NFE_Consulta2_NfeConsulta2 {
            get {
                return ((string)(this["Controles_NFE_Consulta2_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe2/services/NfeInutilizacao2")]
        public string Controles_NFE_Inutilizacao2_NfeInutilizacao2 {
            get {
                return ((string)(this["Controles_NFE_Inutilizacao2_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe2/services/NfeRecepcao2")]
        public string Controles_NFE_Recepcao2_NfeRecepcao2 {
            get {
                return ((string)(this["Controles_NFE_Recepcao2_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe2/services/NfeRetRecepcao2")]
        public string Controles_NFE_RetRecepcao2_NfeRetRecepcao2 {
            get {
                return ((string)(this["Controles_NFE_RetRecepcao2_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe2/services/NfeStatusServico2")]
        public string Controles_NFE_StatusServico2_NfeStatusServico2 {
            get {
                return ((string)(this["Controles_NFE_StatusServico2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.19.133.130/ERP-SGE_WebService/GerarNumNF.asmx")]
        public string Controles_GerarNumNF_GerarNumNF {
            get {
                return ((string)(this["Controles_GerarNumNF_GerarNumNF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.19.133.130/ERP-SGE_WebService/RegistroVenda.asmx")]
        public string Controles_RegistrarPedidoVenda_RegistroVenda {
            get {
                return ((string)(this["Controles_RegistrarPedidoVenda_RegistroVenda"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br:443/nfe2/services/RecepcaoEvento")]
        public string Controles_NFE_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["Controles_NFE_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.19.133.130/ERP-SGE_WebService/UltCompraCliente.asmx")]
        public string Controles_UltimaCompraCliente_UltCompraCliente {
            get {
                return ((string)(this["Controles_UltimaCompraCliente_UltCompraCliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nfe.sefaz.ce.gov.br:80/nfe2/services/NfeAutorizacao")]
        public string Controles_NFE_Autorizacao_NfeAutorizacao {
            get {
                return ((string)(this["Controles_NFE_Autorizacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br/nfe2/services/NfeRetAutorizacao")]
        public string Controles_NFE_RetAutorizacao_NfeRetAutorizacao {
            get {
                return ((string)(this["Controles_NFE_RetAutorizacao_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ce.gov.br/nfe2/services/NfeRetAutorizacao")]
        public string Controles_HNFE_RetAutorizacao_NfeRetAutorizacao {
            get {
                return ((string)(this["Controles_HNFE_RetAutorizacao_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nfeh.sefaz.ce.gov.br:80/nfe2/services/NfeAutorizacao")]
        public string Controles_HNFE_Autorizacao_NfeAutorizacao {
            get {
                return ((string)(this["Controles_HNFE_Autorizacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nfeh.sefaz.ce.gov.br:80/nfe2/services/RecepcaoEvento")]
        public string Controles_HNFE_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["Controles_HNFE_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nfe.sefaz.ce.gov.br:80/nfe4/services/NFeAutorizacao4")]
        public string Controles_NFeAutorizacao4_NFeAutorizacao4 {
            get {
                return ((string)(this["Controles_NFeAutorizacao4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nfe.sefaz.ce.gov.br:80/nfe4/services/NFeConsultaProtocolo4")]
        public string Controles_NFeConsultaProtocolo4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["Controles_NFeConsultaProtocolo4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nfe.sefaz.ce.gov.br:80/nfe4/services/NFeRecepcaoEvento4")]
        public string Controles_NFeRecepcaoEvento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["Controles_NFeRecepcaoEvento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nfe.sefaz.ce.gov.br:80/nfe4/services/NFeRetAutorizacao4")]
        public string Controles_NFeRetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["Controles_NFeRetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx")]
        public string Controles_NFeDistribuicaoDFe_NFeDistribuicaoDFe {
            get {
                return ((string)(this["Controles_NFeDistribuicaoDFe_NFeDistribuicaoDFe"]));
            }
        }
    }
}
