//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SGE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Lucio-TI;Initial Catalog=BD_ERP_SGE;User ID=talimpo; Password=systali" +
            "mpo; MultipleActiveResultSets=True;;")]
        public string BD_ERP_SGE {
            get {
                return ((string)(this["BD_ERP_SGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LUCIO-TI;Initial Catalog=BD_ERP_SGE;User ID=talimpo; Password=systali" +
            "mpo; MultipleActiveResultSets=True;;")]
        public string BD_ERP_SGEConnectionString {
            get {
                return ((string)(this["BD_ERP_SGEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SERVIDOR;Initial Catalog=BD_ERP_SGE;Persist Security Info=True;User I" +
            "D=talimpo; Password=systalimpo; MultipleActiveResultSets=True;;")]
        public string BD_ERP_SGEConnectionString1 {
            get {
                return ((string)(this["BD_ERP_SGEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LUCIO-NOTEBOOK;Initial Catalog=BD_ERP_SGE;User ID=talimpo; Password=s" +
            "ystalimpo; MultipleActiveResultSets=True;")]
        public string BD_ERP_SGEConnectionString2 {
            get {
                return ((string)(this["BD_ERP_SGEConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Trabalho;Initial Catalog=BD_ERP_SGE;Integrated Security=True")]
        public string BD_ERP_SGEConnectionString3 {
            get {
                return ((string)(this["BD_ERP_SGEConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Trabalho;Initial Catalog=BD_ERP_SGE;Persist Security Info=True;User I" +
            "D=talimpo;Password=systalimpo")]
        public string BD_ERP_SGEConnectionString4 {
            get {
                return ((string)(this["BD_ERP_SGEConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LUCIO-TI\\SQL2016;Initial Catalog=BD_ERP_SGE;Persist Security Info=Tru" +
            "e;User ID=talimpo;Password=systalimpo")]
        public string BD_ERP_SGEConnectionString5 {
            get {
                return ((string)(this["BD_ERP_SGEConnectionString5"]));
            }
        }
    }
}
