//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controles.UltimaCompraCliente {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UltCompraClienteSoap", Namespace="http://tempuri.org/")]
    public partial class UltCompraCliente : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UltimaCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback UltimoOrcamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UltCompraCliente() {
            this.Url = global::Controles.Properties.Settings.Default.Controles_UltimaCompraCliente_UltCompraCliente;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UltimaCompraCompletedEventHandler UltimaCompraCompleted;
        
        /// <remarks/>
        public event UltimoOrcamentoCompletedEventHandler UltimoOrcamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UltimaCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode UltimaCompra(string CNPJCPF) {
            object[] results = this.Invoke("UltimaCompra", new object[] {
                        CNPJCPF});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void UltimaCompraAsync(string CNPJCPF) {
            this.UltimaCompraAsync(CNPJCPF, null);
        }
        
        /// <remarks/>
        public void UltimaCompraAsync(string CNPJCPF, object userState) {
            if ((this.UltimaCompraOperationCompleted == null)) {
                this.UltimaCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUltimaCompraOperationCompleted);
            }
            this.InvokeAsync("UltimaCompra", new object[] {
                        CNPJCPF}, this.UltimaCompraOperationCompleted, userState);
        }
        
        private void OnUltimaCompraOperationCompleted(object arg) {
            if ((this.UltimaCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UltimaCompraCompleted(this, new UltimaCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UltimoOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode UltimoOrcamento(string CNPJCPF, int IdServidor) {
            object[] results = this.Invoke("UltimoOrcamento", new object[] {
                        CNPJCPF,
                        IdServidor});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void UltimoOrcamentoAsync(string CNPJCPF, int IdServidor) {
            this.UltimoOrcamentoAsync(CNPJCPF, IdServidor, null);
        }
        
        /// <remarks/>
        public void UltimoOrcamentoAsync(string CNPJCPF, int IdServidor, object userState) {
            if ((this.UltimoOrcamentoOperationCompleted == null)) {
                this.UltimoOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUltimoOrcamentoOperationCompleted);
            }
            this.InvokeAsync("UltimoOrcamento", new object[] {
                        CNPJCPF,
                        IdServidor}, this.UltimoOrcamentoOperationCompleted, userState);
        }
        
        private void OnUltimoOrcamentoOperationCompleted(object arg) {
            if ((this.UltimoOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UltimoOrcamentoCompleted(this, new UltimoOrcamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UltimaCompraCompletedEventHandler(object sender, UltimaCompraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UltimaCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UltimaCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UltimoOrcamentoCompletedEventHandler(object sender, UltimoOrcamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UltimoOrcamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UltimoOrcamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591