//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controles.Serv_SaldoEstoque {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaSaldoSoap", Namespace="http://tempuri.org/")]
    public partial class ConsultaSaldo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaldoEstoqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrevEntregaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DtBalancoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaSaldo() {
            this.Url = global::Controles.Properties.Settings.Default.Controles_Serv_SaldoEstoque_ConsultaSaldo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaldoEstoqueCompletedEventHandler SaldoEstoqueCompleted;
        
        /// <remarks/>
        public event PrevEntregaCompletedEventHandler PrevEntregaCompleted;
        
        /// <remarks/>
        public event DtBalancoCompletedEventHandler DtBalancoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaldoEstoque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal SaldoEstoque(string Ref, string NomeServidor, string Porta) {
            object[] results = this.Invoke("SaldoEstoque", new object[] {
                        Ref,
                        NomeServidor,
                        Porta});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoEstoqueAsync(string Ref, string NomeServidor, string Porta) {
            this.SaldoEstoqueAsync(Ref, NomeServidor, Porta, null);
        }
        
        /// <remarks/>
        public void SaldoEstoqueAsync(string Ref, string NomeServidor, string Porta, object userState) {
            if ((this.SaldoEstoqueOperationCompleted == null)) {
                this.SaldoEstoqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoEstoqueOperationCompleted);
            }
            this.InvokeAsync("SaldoEstoque", new object[] {
                        Ref,
                        NomeServidor,
                        Porta}, this.SaldoEstoqueOperationCompleted, userState);
        }
        
        private void OnSaldoEstoqueOperationCompleted(object arg) {
            if ((this.SaldoEstoqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoEstoqueCompleted(this, new SaldoEstoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrevEntrega", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrevEntrega(string Ref, string NomeServidor, string Porta) {
            object[] results = this.Invoke("PrevEntrega", new object[] {
                        Ref,
                        NomeServidor,
                        Porta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PrevEntregaAsync(string Ref, string NomeServidor, string Porta) {
            this.PrevEntregaAsync(Ref, NomeServidor, Porta, null);
        }
        
        /// <remarks/>
        public void PrevEntregaAsync(string Ref, string NomeServidor, string Porta, object userState) {
            if ((this.PrevEntregaOperationCompleted == null)) {
                this.PrevEntregaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrevEntregaOperationCompleted);
            }
            this.InvokeAsync("PrevEntrega", new object[] {
                        Ref,
                        NomeServidor,
                        Porta}, this.PrevEntregaOperationCompleted, userState);
        }
        
        private void OnPrevEntregaOperationCompleted(object arg) {
            if ((this.PrevEntregaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrevEntregaCompleted(this, new PrevEntregaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DtBalanco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DtBalanco(string Ref, string NomeServidor, string Porta) {
            object[] results = this.Invoke("DtBalanco", new object[] {
                        Ref,
                        NomeServidor,
                        Porta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DtBalancoAsync(string Ref, string NomeServidor, string Porta) {
            this.DtBalancoAsync(Ref, NomeServidor, Porta, null);
        }
        
        /// <remarks/>
        public void DtBalancoAsync(string Ref, string NomeServidor, string Porta, object userState) {
            if ((this.DtBalancoOperationCompleted == null)) {
                this.DtBalancoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDtBalancoOperationCompleted);
            }
            this.InvokeAsync("DtBalanco", new object[] {
                        Ref,
                        NomeServidor,
                        Porta}, this.DtBalancoOperationCompleted, userState);
        }
        
        private void OnDtBalancoOperationCompleted(object arg) {
            if ((this.DtBalancoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DtBalancoCompleted(this, new DtBalancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SaldoEstoqueCompletedEventHandler(object sender, SaldoEstoqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoEstoqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoEstoqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PrevEntregaCompletedEventHandler(object sender, PrevEntregaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrevEntregaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrevEntregaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DtBalancoCompletedEventHandler(object sender, DtBalancoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DtBalancoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DtBalancoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591